export const listData = [
  {
    id: 1,
    title:
      "ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit",
    img: "http://dummyimage.com/x.png/cc0000/ffffff",
    bedRooms: 2,
    bathRooms: 5,
    price: 6913,
    address: "09173 Buena Vista Plaza",
    latitude: 41.420018,
    longitude: 128.200789,
  },
  {
    id: 2,
    title:
      "ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem",
    img: "http://dummyimage.com/x.png/5fa2dd/ffffff",
    bedRooms: 7,
    bathRooms: 4,
    price: 54499,
    address: "00 Messerschmidt Park",
    latitude: 55.321347,
    longitude: 42.16866,
  },
  {
    id: 3,
    title:
      "vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed",
    img: "http://dummyimage.com/x.png/ff4444/ffffff",
    bedRooms: 10,
    bathRooms: 8,
    price: 46379,
    address: "144 Sloan Park",
    latitude: 57.719258,
    longitude: 11.9417454,
  },
  {
    id: 4,
    title:
      "vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non",
    img: "http://dummyimage.com/x.png/5fa2dd/ffffff",
    bedRooms: 6,
    bathRooms: 9,
    price: 39947,
    address: "09932 Northport Lane",
    latitude: 46.215926,
    longitude: -63.0886099,
  },
  {
    id: 5,
    title:
      "cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum",
    img: "http://dummyimage.com/x.png/5fa2dd/ffffff",
    bedRooms: 4,
    bathRooms: 2,
    price: 33444,
    address: "78810 Thackeray Street",
    latitude: 14.3758164,
    longitude: 121.0390378,
  },
  {
    id: 6,
    title:
      "felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing",
    img: "http://dummyimage.com/x.png/cc0000/ffffff",
    bedRooms: 5,
    bathRooms: 6,
    price: 6890,
    address: "3580 Hoard Crossing",
    latitude: 25.130594,
    longitude: 109.768451,
  },
  {
    id: 7,
    title: "quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis",
    img: "http://dummyimage.com/x.png/ff4444/ffffff",
    bedRooms: 8,
    bathRooms: 3,
    price: 14930,
    address: "16968 Logan Parkway",
    latitude: 37.0909826,
    longitude: 138.1698009,
  },
  {
    id: 8,
    title:
      "nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit",
    img: "http://dummyimage.com/x.png/cc0000/ffffff",
    bedRooms: 10,
    bathRooms: 2,
    price: 47896,
    address: "85911 Browning Junction",
    latitude: 37.347409,
    longitude: 115.965874,
  },
  {
    id: 9,
    title:
      "at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante",
    img: "http://dummyimage.com/x.png/5fa2dd/ffffff",
    bedRooms: 10,
    bathRooms: 1,
    price: 58215,
    address: "44 Jana Parkway",
    latitude: 58.3234233,
    longitude: 15.602105,
  },
  {
    id: 10,
    title:
      "felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis",
    img: "http://dummyimage.com/x.png/cc0000/ffffff",
    bedRooms: 6,
    bathRooms: 1,
    price: 52959,
    address: "04424 Ridgeway Drive",
    latitude: 55.111901,
    longitude: 83.8869856,
  },
];
